### ISSUE TITLE
ILIAS 8: Call to undefined method ilCronManager::getCronJobData() 

### ISSUE THREAD

**Issue by colin-kiegel** [HochschuleLuzern/NotifyOnCronFailure#2]
Unter ILIAS 8 läuft das Plugin neuerdings in folgenden Fehler:

ERROR: ilCronManagerImpl::runJobManual:376 **Call to undefined method ilCronManager::getCronJobData()**  

```
#0 /srv/ilias/Services/Cron/classes/class.ilCronManagerImpl.php(169): ilNotifyOnCronFailureNotify->run()
#1 /srv/ilias/Services/Cron/classes/class.ilCronManagerImpl.php(104): ilCronManagerImpl->runJob(Object(ilNotifyOnCronFailureNotify), Object(ilObjUser), Array, true)
#2 /srv/ilias/Services/Cron/classes/class.ilCronManagerGUI.php(376): ilCronManagerImpl->runJobManual('pl__NotifyOnCro...', Object(ilObjUser))
#3 /srv/ilias/Services/Cron/classes/class.ilCronManagerGUI.php(129): ilCronManagerGUI->confirmedRun()
#4 /srv/ilias/Services/UICore/classes/class.ilCtrl.php(199): ilCronManagerGUI->executeCommand()
#5 /srv/ilias/Modules/SystemFolder/classes/class.ilObjSystemFolderGUI.php(172): ilCtrl->forwardCommand(Object(ilCronManagerGUI))
#6 /srv/ilias/Services/UICore/classes/class.ilCtrl.php(199): ilObjSystemFolderGUI->executeCommand()
#7 /srv/ilias/Services/Administration/classes/class.ilAdministrationGUI.php(237): ilCtrl->forwardCommand(Object(ilObjSystemFolderGUI))
#8 /srv/ilias/Services/UICore/classes/class.ilCtrl.php(199): ilAdministrationGUI->executeCommand()
#9 /srv/ilias/Services/UICore/classes/class.ilCtrl.php(174): ilCtrl->forwardCommand(Object(ilAdministrationGUI))
#10 /srv/ilias/ilias.php(24): ilCtrl->callBaseClass()
```

**Comment by kergomard** [comment]
Thank you very much for the Issue @colin-kiegel ! This way we don't loose track of it! I will leave the decision on how to proceed fully to the University of Applied Sciences Lucern.

Best,
@kergomard
